### ISSUE TITLE
Where is the code of function DoublyStochastic?

### ISSUE THREAD

**Issue by BinruiShen** [oxfordcontrol/DoublyStochastic.jl#1]
I find the introduction of DoublyStochastic function, but I do not find its code from DoublyStochastic.jl.

**Comment by nrontsis** [comment]
Is this resolved? It could be that I forgot to include some file when creating the repo, in which case I can dig up my dropbox backup and upload it.

**Comment by nrontsis** [comment]
I have now updated the Readme, let me know if this works for you.

**Comment by BinruiShen** [comment]
Thanks for your kind reply! I know the function know. I am learning julia to run your codes, while I am too inexperienced  to use them. When I try to use admm_dense:

**A=[2 3 4; 4 5 6; 1 3 5]
solve(A)**
there is an error：**ERROR: InexactError: Int64(1.7).**

As a beginner, I do not know why it can not run. Could you please give an simple example for it?
I appreciate your help.

**Comment by nrontsis** [comment]
The code only works for floats. Can you thus try with?
`A=[2.0 3.0 4.0; 4.0 5.0 6.0; 1.0 3.0 5.0]`

**Comment by BinruiShen** [comment]
It works! Thank you so much!
